[project]
name = "snake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
snake ="main:main"

[tool.setuptools]
py-modules = ["main", "snake", "food", "scoreboard"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"